services:
  - xvfb

os:
  - linux
language: python
python:
  - "3.7"
  - "3.5"
  - "3.6"
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install  coverage ordereddict
  - pip install  coveralls mock
  - pip install  pytest pytest-cov pytest-mock --upgrade

script:
  - python -m pytest -v --durations=10 test/ --cov=easydev --cov-report term-missing

after_success:
  coveralls

